version: '3.5'
services:
  api1: # API - Instância 01
    image: rodrigograudo/rinha-de-backend-2023-q3-nestjs:latest
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    environment:
      - DATABASE_HOST=db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    image: rodrigograudo/rinha-de-backend-2023-q3-nestjs:latest
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    environment:
      - DATABASE_HOST=db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rinha
    ports:
      - "3306:3306"
    command: mysqld --innodb_buffer_pool_size=1250M --innodb_buffer_pool_instances=1 --innodb_log_file_size=160M
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
